### ISSUE TITLE
Question: What is the best way to import a set of icons eg a set of country flags?

### ISSUE THREAD

**Issue by flowt-au** [hawkeye64/quasar-extras-svg-icons#23]
Hi Jeff,
As a test I have used your example to import a single flag:
```
import { flagAU } from 'quasar-extras-svg-icons/country-flag-icons'
created () {
    this.flagAU = flagAU
}
<q-icon :name="flagAU" size="xs" class="q-ml-xs" />
```
All great!

So, if I have a set of country codes eg`['AU', 'FR', 'NZ']` which I want to use in (say) a select box, what would be the best way to go about importing the svgs for that set? ie the required code list is dynamic.

Thanks,
Murray

**Comment by flowt-au** [comment]
I am using app-webpack

**Comment by hawkeye64** [comment]
@flowt-au You want to do something like this: https://github.com/hawkeye64/iconexplorer.app/blob/master/src/assets/store.js#L278-L293

The comments direct webpack so it's important to have the correct info.

**Comment by flowt-au** [comment]
Aha! I see. Yes, thank you! :-)
