### ISSUE TITLE
Possible to add to quasar.config.js and globally replace icons?

### ISSUE THREAD

**Issue by CharlieDigital** [hawkeye64/quasar-extras-svg-icons#24]
Can't quite figure out if it is possible to globally replace the icon set so that it can be accessed like this:

_(Using Tabler `tab` as example)_

```
<QIcon name="tab-hexagon" />
```

Instead of importing each icon individually.

Thanks!

**Comment by hawkeye64** [comment]
That would only work with web fonts (which is not the design of this package).

**Comment by CharlieDigital** [comment]
Got it; thanks for the clarification.
