### ISSUE TITLE
typos in README.md

### ISSUE THREAD

**Issue by seoyoungjin** [hawkeye64/quasar-extras-svg-icons#25]
Example

- pixelarticons -> pixelart-icons
- remix-icon -> remix-icons

Table

Radix-UI Icon  package is  quasar-extras-svg-icons/remix-icons.
This may be quasar-extras-svg-icons/radix-icons?

**Comment by hawkeye64** [comment]
Thanks for taking the time to let me know about this.
It's been fixed with the v1.26.0 release.
