### ISSUE TITLE
[Feature Request] Add webfont medical icons svg

### ISSUE THREAD

**Issue by lukadriel7** [hawkeye64/quasar-extras-svg-icons#3]
Hello, thank you for the work.
I recently found this library and I thought it might be a good fit to add webfont-medical-icons to it.
I personally created a version which is compatible with quasar svg icons but since this library is officially supported, maybe it could be added here ? this is the [link](https://github.com/lukadriel7/webfont-medical-icons)

**Comment by hawkeye64** [comment]
Thanks for letting me know about these icons. I took them from here: https://github.com/samcome/webfont-medical-icons
They will be in the quasar-extras-svg-icons v1.7.0 releasing later this week

Also, on your page, you have some confusing code:
![image](https://user-images.githubusercontent.com/10262924/144265452-755bea6c-f1e2-4f24-a32d-b1026fa5e034.png)
On this image, you are using `tabMenu` but not importing it.

**Comment by lukadriel7** [comment]
Thanks I will change it
