### ISSUE TITLE
feat: Add HealthIcons and maybe others

### ISSUE THREAD

**Issue by lukadriel7** [hawkeye64/quasar-extras-svg-icons#4]
Hello, It's me again.
There is another icon set that would make a great addition, the [healthicons project](https://github.com/resolvetosavelives/healthicons).
Also just in case, I think you can find other interesting icon sets at [Iconify](https://icon-sets.iconify.design/).

I will wait to see which icons you add to your library and maybe create a separate library for those which didn't make the cut.
Thanks again for this great project.

**Comment by hawkeye64** [comment]
I'll give it a try. Not all icon sets convert to the flattened SVG. We'll see if they use anything that can't be converted.

**Comment by hawkeye64** [comment]
@lukadriel7 I got them integrated. Only one glitch which was filename based (!.svg) that was easily fixable.

They will be available in v1.7.0 when released. Thanks for your help finding good sets of icons :heart:

**Comment by lukadriel7** [comment]
Happy to help 😁

**Comment by hawkeye64** [comment]
In the meantime, you can check them out in the docs before release: https://quasar-extras-svg-icons.netlify.app/all-about-quasar-extras-svg-icons/icon-finder
