### ISSUE TITLE
[Feature Request] Add IBM Carbon Icons and Pictograms

### ISSUE THREAD

**Issue by lukadriel7** [hawkeye64/quasar-extras-svg-icons#6]
Hello,
The Carbon Icon set from IBM seems to have some unique icons and pictograms.
They would be great here too.
[IBM Carbon Icons](https://www.carbondesignsystem.com/guidelines/icons/library/)
[IBM Carbon Pictograms](https://www.carbondesignsystem.com/guidelines/pictograms/library/)

**Comment by hawkeye64** [comment]
I think I tried adding these to quasar/extras at one point and failed. The parser in this package had grown so much more, so I'm willing to try again.

**Comment by hawkeye64** [comment]
Both of them were added and are now released in v1.7.0
