### ISSUE TITLE
[Bug]: Can't use 'currentColor' on Health Icons

### ISSUE THREAD

**Issue by hawkeye64** [hawkeye64/quasar-extras-svg-icons#7]
This needs a filter treatment.

**Comment by lukadriel7** [comment]
Hey, I was just checking the reason and found out why.
You need to remove the following properties from the Icons:

This one create a box around some icons like `healthFilledWheelchair`, I personally think it isn't needed
`M0 0H48V48H0z@@fill:#fff;`
The following two are the culprits preventing the change of color
`fill:none;`
`fill:#333;`

**Comment by hawkeye64** [comment]
Thanks for taking the time to look into this. It needs a styles filter. I may not be able to get to it until the weekend.

**Comment by hawkeye64** [comment]
The `fill:none` is inconsequential as the second `fill` will override it. I need to come up with a way of handling duplicate attributes to cut down on the size. The `fill:none` is either coming from attributes on the `<SVG ...` tag or a `<g ...` tag. Neither of those can be handled by the Quasar QIcon implementation, so I make the proceeding paths inherit them directly if found.

Anyway, this is fixed and will be in the v1.7.1 release.
