### ISSUE TITLE
[Bug]: Carbon pictograms not showing correctly

### ISSUE THREAD

**Issue by lukadriel7** [hawkeye64/quasar-extras-svg-icons#8]
Hello, I checked the carbon pictograms and It seems they were incorrectly parsed.
In the svg icons, they used a tab to separate while in this package, tabs are replaced with commas.
It results in icons being displayed incorrectly. Using tabs will correct the issue.
 e.g: cloud--computing pictogram
this library:
`M16,31.36C7.53,31.36,0.64,24.47,0.64,16S7.53,0.64,16,0.64S31.36,7.53,31.36,16,S24.47,31.36,16,31.36z M15.385,30.627c0.204,0.009,0.409,0.013,0.615,0.013c4.741,0,8.963-2.265,11.64-5.77V12.008h0.721v11.831,c1.442-2.268,2.279-4.957,2.279-7.839c0-1.999-0.402-3.904-1.13-5.641L18.363,3.924l0.36-0.624l10.249,5.917,c-2.174-4.141-6.273-7.119-11.101-7.738L6.723,7.916l-0.36-0.624l10.252-5.919C16.412,1.364,16.206,1.36,16,1.36,c-4.741,0-8.963,2.266-11.64,5.771v12.862H3.64V8.161C2.197,10.429,1.36,13.119,1.36,16c0,1.998,0.402,3.903,1.13,5.641,l11.147,6.436l-0.36,0.623L3.028,22.782c2.174,4.142,6.273,7.12,11.101,7.739l11.148-6.437l0.359,0.623L15.385,30.627z`
The original svg
`M16,31.36C7.53,31.36,0.64,24.47,0.64,16S7.53,0.64,16,0.64S31.36,7.53,31.36,16	S24.47,31.36,16,31.36z M15.385,30.627c0.204,0.009,0.409,0.013,0.615,0.013c4.741,0,8.963-2.265,11.64-5.77V12.008h0.721v11.831	c1.442-2.268,2.279-4.957,2.279-7.839c0-1.999-0.402-3.904-1.13-5.641L18.363,3.924l0.36-0.624l10.249,5.917	c-2.174-4.141-6.273-7.119-11.101-7.738L6.723,7.916l-0.36-0.624l10.252-5.919C16.412,1.364,16.206,1.36,16,1.36	c-4.741,0-8.963,2.266-11.64,5.771v12.862H3.64V8.161C2.197,10.429,1.36,13.119,1.36,16c0,1.998,0.402,3.903,1.13,5.641	l11.147,6.436l-0.36,0.623L3.028,22.782c2.174,4.142,6.273,7.12,11.101,7.739l11.148-6.437l0.359,0.623L15.385,30.627z`

**Comment by hawkeye64** [comment]
Thanks for letting me know. I'll see what I can do, but it may have to wait until the weekend.

Btw, nice sharp eagle-eye you got there to have noticed that.

The tabs vs comma issue, is there something in the spec about tabs, or can it just be any whitespace?

**Comment by hawkeye64** [comment]
Actually, I m not seeing a difference in the pictograms.

Here is the one we are generating:
![image](https://user-images.githubusercontent.com/10262924/144626974-db9543ad-bb42-46d5-8ddd-6d1b5a222587.png)

and here is the one in the repo:
![image](https://user-images.githubusercontent.com/10262924/144627051-8b061927-cf53-4faa-a7de-5751ec9788ea.png)

Can you see any with visible differences?

**Comment by lukadriel7** [comment]
Sorry for the late reply, I was busy all day. I think the issue is with Firefox. You should open the docs on Firefox to see how the pictograms appear.

**Comment by hawkeye64** [comment]
Closing this one for #9
